// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXEnagYmgZHbVk46GyEpSD7gzI2dHLruk',
    appId: '1:563044592197:web:493c4d5438762b327a512c',
    messagingSenderId: '563044592197',
    projectId: 'safeshield-9d1ed',
    authDomain: 'safeshield-9d1ed.firebaseapp.com',
    storageBucket: 'safeshield-9d1ed.appspot.com',
    measurementId: 'G-YVF3JRH7F9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyjx9XQszHECXrZfIHtvWAXF8KLS-2TIU',
    appId: '1:563044592197:android:5ef1cac10716fe3d7a512c',
    messagingSenderId: '563044592197',
    projectId: 'safeshield-9d1ed',
    storageBucket: 'safeshield-9d1ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpRpe1uFPje004GjvMZIHWurDQtY1-xL4',
    appId: '1:563044592197:ios:eb0b7a5644d6bc627a512c',
    messagingSenderId: '563044592197',
    projectId: 'safeshield-9d1ed',
    storageBucket: 'safeshield-9d1ed.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpRpe1uFPje004GjvMZIHWurDQtY1-xL4',
    appId: '1:563044592197:ios:eb0b7a5644d6bc627a512c',
    messagingSenderId: '563044592197',
    projectId: 'safeshield-9d1ed',
    storageBucket: 'safeshield-9d1ed.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXEnagYmgZHbVk46GyEpSD7gzI2dHLruk',
    appId: '1:563044592197:web:b45beea16fd618a57a512c',
    messagingSenderId: '563044592197',
    projectId: 'safeshield-9d1ed',
    authDomain: 'safeshield-9d1ed.firebaseapp.com',
    storageBucket: 'safeshield-9d1ed.appspot.com',
    measurementId: 'G-C92CX1NHHK',
  );

}